### ISSUE TITLE
Erro ao tentar baixar o JDK 

### ISSUE THREAD

**Issue by JohannBandelow** [paulorievrs/java4noobs#11]
Quando entro no link anexado para baixar o JDK o site da erro, creio que só atualizando o link pela nova versão do JDK 15 já daria certo :)

**Comment by FerroEduardo** [comment]
Poderia detalhar mais? Eu consigo acessar todos os links que estão [aqui](https://github.com/paulorievrs/java4noobs/blob/master/2%20-%20Ambiente/2.1-Ambiente-Windows.md)

**Comment by JohannBandelow** [comment]
Ele vai até o site da Oracle para fazer o download do JDK, tudo tranquilo. Porém quando seleciona as versões para windows para fazer o download ele te redireciona pra esse site : https://www.oracle.com/splash/www/index.html .
Eu consegui resolver esse problema baixando uma versão mais atualizada do JDK, que achei no google, no próprio site da oracle

**Comment by FerroEduardo** [comment]
Que estranho, consegui fazer o download dos arquivos de instalação tanto [aqui](https://www.java.com/pt_BR/download/), quanto [aqui](https://www.oracle.com/br/java/technologies/javase/javase-jdk8-downloads.html). A única diferença é que no segundo link ele pede a conta da Oracle.

**Comment by paulorievrs** [comment]
Pra mim tá ok também.

**Comment by JohannBandelow** [comment]
Ok, pode ter sido coisa do meu browser ou momentâneo do site, estou fechando a issue 👎
