### ISSUE TITLE
Conserto de Bug.

### ISSUE THREAD

**Issue by FerreiraWalter** [paulorievrs/java4noobs#12]
No inicio foi criado uma **varável "contador"** mas na **Estrutura de Repetição** virou apenas **"cont"**
Eu posso estar errado, mas no programa está dando erro.
Esse erro está em todos os exemplos

![pessoa](https://user-images.githubusercontent.com/69780634/103172832-1a801400-4835-11eb-90c2-16def5005c43.png)

**Comment by FerroEduardo** [comment]
Obrigado por avisar @FerreiraWalter
