### ISSUE TITLE
[Implementação] ArrayList/LinkedList

### ISSUE THREAD

**Issue by midhatdrops** [paulorievrs/java4noobs#17]
Queria trazer uma PR a respeito de ArrayList e LinkedList, não é um assunto exclusivo de Java, mas considero ser algo do módulo intermediário.

Gostaria de saber se posso atualizar o arquivo de funções e de Array para adicionar expressões Lambda e a API streams.

**Comment by FerroEduardo** [comment]
Seria ótimo! Pode fazer o PR

**Comment by FerroEduardo** [comment]
Quando for assim, pode enviar o PR direto. Não precisa pedir autorização para contribuir

**Comment by midhatdrops** [comment]
Segue [PR#18](https://github.com/paulorievrs/java4noobs/pull/18) .
